pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/endalkyz/My-portfolio-project.git'
            }
        }

        stage('Build Image') {
            steps {
                dir('backend/portfolio') {
                    sh 'docker build -t portfolio:test .'
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('backend/portfolio') {
                    sh '''
                    docker run --rm portfolio:test \
                    python manage.py test
                    '''
                }
            }
        }
    }
}
