pipeline {
    agent any

    environment {
        DJANGO_SETTINGS_MODULE = 'portfolio.settings'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/endalkyz/My-portfolio-project.git'
            }
        }

        stage('Build Docker') {
            steps {
                sh 'docker-compose build'
            }
        }

        stage('Run Migrations') {
            steps {
                sh 'docker-compose run web python manage.py migrate'
            }
        }

        stage('Test') {
            steps {
                sh 'docker-compose run web python manage.py test'
            }
        }

        stage('Deploy') {
            steps {
                sh 'docker-compose up -d'
            }
        }
    }

    post {
        always {
            sh 'docker-compose down'
        }
    }
}
