pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/endalkyz/My-portfolio-project.git'
            }
        }

        stage('Build Docker') {
            steps {
                dir('backend/portfolio') {
                    bat 'docker-compose build'
                }
            }
        }

        stage('Run Migrations') {
            steps {
                dir('backend/portfolio') {
                    bat 'docker-compose run web python manage.py migrate'
                }
            }
        }

        stage('Test') {
            steps {
                dir('backend/portfolio') {
                    bat 'docker-compose run web python manage.py test'
                }
            }
        }

        stage('Deploy') {
            steps {
                dir('backend/portfolio') {
                    bat 'docker-compose up -d'
                }
            }
        }
    }

    post {
        always {
            dir('backend/portfolio') {
                bat 'docker-compose down'
            }
        }
    }
}
